---------------------0---------------------
USE [IAMC_Ficohsa_PRD_NA];
GO
SET ANSI_NULLS ON;
GO
SET QUOTED_IDENTIFIER ON;
GO
CREATE TABLE [Frs_CompositeContract_Identity] (
[Id] uniqueidentifier NOT NULL,
[ReadOnly] bit NULL,
[LoginID] nvarchar(50) NULL,
[RecId] char(32) NOT NULL,
[CompositeType] varchar(50) NOT NULL,
[Password] varchar(160) NULL,
[IsInternal] bit NULL,
[IsImported] bit NULL,
[IsDisabled] bit NULL,
[InternalPwdDateTime] datetime NULL,
[TempInternalAuthPassword] varchar(160) NULL,
[TempPwdDatetime] datetime NULL,
[PasswordExpiration] bit NULL,
[LastExternalLoginId] varchar(50) NULL,
[IsNamedUser] bit NULL,
[RemoteControlPwd] varchar(100) NULL,
[RemoteControlUID] varchar(100) NULL,
[NamedLicenseBundle] varchar(100) NULL,
[NamedLicenseBundle_Valid] varchar(32) NULL,
[LockDate] datetime NULL,
[LoginAttemptCount] smallint NULL,
[LockType] nvarchar(15) NULL,
[GlobalId] uniqueidentifier NULL)
ON [PRIMARY];
GO


----------------------1---------------------
USE [IAMC_Ficohsa_PRD_NA];
GO
SET ANSI_NULLS ON;
GO
SET QUOTED_IDENTIFIER ON;
GO
CREATE TABLE [Frs_def_role_assignment] (
[SourceID] char(32) NOT NULL,
[TargetID] char(32) NOT NULL)
ON [PRIMARY];
GO

----------------------2---------------------

USE [IAMC_Ficohsa_PRD_NA];
GO
SET ANSI_NULLS ON;
GO
SET QUOTED_IDENTIFIER ON;
GO
CREATE TABLE [Frs_def_role] (
[RecId] char(32) NOT NULL,
[LastModDateTime] datetime NULL,
[LastModBy] nvarchar(100) NULL,
[CreatedDateTime] datetime NULL,
[CreatedBy] nvarchar(100) NULL,
[RoleID] nvarchar(100) NOT NULL,
[DisplayName] nvarchar(100) NULL,
[DesktopName] nvarchar(100) NULL,
[ParentRole_RecID] varchar(32) NULL,
[ParentRole_Category] varchar(100) NULL,
[ReadOnly] bit NULL,
[DesktopName_de] nvarchar(100) NULL,
[DesktopName_es] nvarchar(100) NULL,
[DesktopName_fr] nvarchar(100) NULL,
[DesktopName_nl] nvarchar(100) NULL,
[DesktopName_pt_BR] nvarchar(100) NULL,
[DesktopName_ru] nvarchar(100) NULL,
[DesktopName_ja] nvarchar(100) NULL,
[DesktopName_zh_CN] nvarchar(100) NULL,
[DesktopName_it] nvarchar(100) NULL,
[DesktopName_pl] nvarchar(100) NULL,
[DesktopName_zh_TW] nvarchar(100) NULL,
[DisplayName_de] nvarchar(100) NULL,
[DisplayName_es] nvarchar(100) NULL,
[DisplayName_fr] nvarchar(100) NULL,
[DisplayName_nl] nvarchar(100) NULL,
[DisplayName_pt_BR] nvarchar(100) NULL,
[DisplayName_ru] nvarchar(100) NULL,
[DisplayName_ja] nvarchar(100) NULL,
[DisplayName_zh_CN] nvarchar(100) NULL,
[DisplayName_it] nvarchar(100) NULL,
[DisplayName_pl] nvarchar(100) NULL,
[DisplayName_zh_TW] nvarchar(100) NULL,
[DisplayName_en_GB] nvarchar(100) NULL,
[DesktopName_en_GB] nvarchar(100) NULL)
ON [PRIMARY];
GO


----------------------3---------------------

USE [IAMC_Ficohsa_PRD_NA];
GO
SET ANSI_NULLS ON;
GO
SET QUOTED_IDENTIFIER ON;
GO
CREATE TABLE [Incident] (
[ActualCategory] varchar(60) NULL,
[ActualCategory_Valid] varchar(32) NULL,
[Category] nvarchar(60) NULL,
[Category_Valid] varchar(32) NULL,
[CauseCode] nvarchar(60) NULL,
[CauseCode_Valid] varchar(32) NULL,
[ClosedBy] nvarchar(100) NULL,
[ClosedDateTime] datetime NULL,
[ClosedDuration] decimal(10, 0) NULL,
[CreatedBy] nvarchar(100) NULL,
[CreatedDateTime] datetime NULL,
[Email] nvarchar(255) NULL,
[FirstCallResolution] bit NULL,
[Impact] nvarchar(30) NULL,
[Impact_Valid] varchar(32) NULL,
[IncidentNumber] decimal(10, 0) NULL,
[IsNotification] bit NULL,
[IsVIP] bit NULL,
[IsWorkAround] bit NULL,
[LastModBy] nvarchar(100) NULL,
[LastModDateTime] datetime NULL,
[Phone] varchar(25) NULL,
[Priority] nvarchar(25) NULL,
[Priority_Valid] varchar(32) NULL,
[ProfileFullName] nvarchar(255) NULL,
[ProfileLink_RecID] varchar(32) NULL,
[ProfileLink_Category] varchar(100) NULL,
[RecId] char(32) NOT NULL,
[Resolution] nvarchar(MAX) NULL,
[Service] nvarchar(100) NULL,
[Service_Valid] varchar(32) NULL,
[SLA] nvarchar(100) NULL,
[SLALink_RecID] varchar(32) NULL,
[SLALink_Category] varchar(100) NULL,
[Source] nvarchar(40) NULL,
[Source_Valid] varchar(32) NULL,
[Status] nvarchar(40) NULL,
[Status_Valid] varchar(32) NULL,
[Subject] nvarchar(255) NULL,
[Symptom] nvarchar(MAX) NULL,
[Urgency] nvarchar(30) NULL,
[Urgency_Valid] varchar(32) NULL,
[LoginId] nvarchar(200) NULL,
[Owner] nvarchar(100) NULL,
[Owner_Valid] varchar(32) NULL,
[OwnerTeam] nvarchar(100) NULL,
[OwnerTeam_Valid] varchar(32) NULL,
[OwnerType] varchar(30) NULL,
[AlternateContactLink_RecID] varchar(32) NULL,
[AlternateContactLink_Category] varchar(100) NULL,
[ResolvedDateTime] datetime NULL,
[ResolvedBy] nvarchar(100) NULL,
[HoursOfOperation] nvarchar(100) NULL,
[HoursOfOperation_Valid] varchar(32) NULL,
[OwnerEmail] nvarchar(255) NULL,
[OwnerTeamEmail] nvarchar(255) NULL,
[CustomerLocation] nvarchar(100) NULL,
[IsReportedByAlternateContact] bit NULL,
[ResolutionEscLink_RecID] varchar(32) NULL,
[ResolutionEscLink_Category] varchar(100) NULL,
[ResponseEscLink_RecID] varchar(32) NULL,
[ResponseEscLink_Category] varchar(100) NULL,
[WaitingEscLink_RecID] varchar(32) NULL,
[WaitingEscLink_Category] varchar(100) NULL,
[ClosingEscLink_RecID] varchar(32) NULL,
[ClosingEscLink_Category] varchar(100) NULL,
[AlternateContactEmail] nvarchar(255) NULL,
[OrganizationUnitID] nvarchar(60) NULL,
[ReportingOrgUnitID] varchar(64) NULL,
[TypeOfIncident] nvarchar(40) NULL,
[AlternateContactPhone] varchar(25) NULL,
[TeamManagerEmail] nvarchar(255) NULL,
[ProblemLink_Category] varchar(100) NULL,
[ProblemLink_RecID] varchar(32) NULL,
[CustomerDepartment] nvarchar(100) NULL,
[ActualService_Valid] varchar(32) NULL,
[ActualService] nvarchar(100) NULL,
[CostPerMinute] money NULL,
[IsInFinalState] bit NULL,
[IsReclassifiedForResolution] bit NULL,
[KnowledgeLink_Category] varchar(100) NULL,
[KnowledgeLink_RecID] varchar(32) NULL,
[PreviousState] nvarchar(50) NULL,
[ResolvedByIncidentNumber] decimal(10, 2) NULL,
[TotalTimeSpent] decimal(10, 2) NULL,
[RespondedBy] nvarchar(100) NULL,
[RespondedDateTime] datetime NULL,
[OrgUnitLink_Category] varchar(100) NULL,
[OrgUnitLink_RecID] varchar(32) NULL,
[ReportingOrgUnitID_Valid] varchar(32) NULL,
[OwningOrgUnitId_Valid] varchar(32) NULL,
[OwningOrgUnitId] varchar(60) NULL,
[ProgressBarPosition] varchar(25) NULL,
[ResolvedByType] nvarchar(70) NULL,
[ReportedBy] nvarchar(255) NULL,
[CreatedByType] nvarchar(25) NULL,
[SLADisplayText] nvarchar(100) NULL,
[ServiceReqLink_RecID] varchar(32) NULL,
[ServiceReqLink_Category] varchar(100) NULL,
[ReadOnly] bit NULL,
[Cost] money NULL,
[IncidentDetailSummary] nvarchar(1024) NULL,
[IncidentDetailWorkflowTag] varchar(75) NULL,
[Approver] nvarchar(255) NULL,
[IsApprovalNeeded] bit NULL,
[IsDSMTaskExisted] bit NULL,
[ApprovalStatus] nvarchar(50) NULL,
[SocialTextHeader] ntext NULL,
[Subcategory] nvarchar(60) NULL,
[Subcategory_Valid] varchar(32) NULL,
[helpdesk_Priority] nvarchar(32) NULL,
[ViewType] nvarchar(32) NULL,
[helpdesk_Priority_Valid] varchar(32) NULL,
[IncidentNetworkUserName] varchar(200) NULL,
[SendSurveyNotification] bit NULL,
[CustomerLocation_Valid] varchar(32) NULL,
[Approver_Valid] varchar(32) NULL,
[EntityLink_RecID] varchar(32) NULL,
[EntityLink_Category] varchar(100) NULL,
[Cost_CurrencyValid] varchar(32) NULL,
[Cost_Currency] varchar(32) NULL,
[CostPerMinute_CurrencyValid] varchar(32) NULL,
[CostPerMinute_Currency] varchar(32) NULL,
[EventCIRecId] varchar(32) NULL,
[IsRelatedIncidentResolutionUpdate] bit NULL,
[IsRelatedIncidentUpdate] bit NULL,
[ServiceOwnerEmail] varchar(255) NULL,
[MasterIncidentLink_RecID] varchar(32) NULL,
[MasterIncidentLink_Category] varchar(100) NULL,
[IsResolvedByMaster] bit NULL,
[IsMasterIncident] bit NULL,
[IsUnRead] bit NULL,
[HRCaseLink_Category] varchar(100) NULL,
[HRCaseLink_RecID] varchar(32) NULL,
[ivnt_RequestforInformationorData] bit NULL,
[ivnt_UpdateRFI] nvarchar(100) NULL,
[AddChatconversationtoActivityHistory] bit NULL,
[ivnt_TeamsUserDetailsLink_Category] varchar(100) NULL,
[ivnt_TeamsUserDetailsLink_RecID] varchar(32) NULL,
[VirimaAssetID] varchar(32) NULL,
[RecommendedCategory] nvarchar(200) NULL,
[RecommendedService] nvarchar(200) NULL,
[RecommendedSubCategory] nvarchar(200) NULL,
[Accuracy] decimal(8, 5) NULL,
[IsRecommended] bit NULL,
[RecomService] nvarchar(200) NULL,
[RecomCategory] nvarchar(200) NULL,
[RecomSubCategory] varchar(200) NULL,
[IsRunTicketClassification] bit NULL,
[Complejidad] varchar(200) NULL,
[Complejidad_Valid] varchar(42) NULL,
[AA_TipoSLA_Valid] varchar(42) NULL,
[AA_TipoSLA] varchar(200) NULL,
[AA_TipoResolucion_Valid] varchar(42) NULL,
[AA_TipoResolucion] varchar(200) NULL,
[AA_TipoActualizacion_Valid] varchar(42) NULL,
[AA_TipoActualizacion] varchar(200) NULL,
[AA_Empresa_Valid] varchar(42) NULL,
[AA_Empresa] varchar(200) NULL,
[AA_Pais_Valid] varchar(42) NULL,
[AA_Pais] varchar(200) NULL,
[AA_Ambiente] varchar(200) NULL,
[AA_Ambiente_Valid] varchar(42) NULL,
[AA_Fecha] datetime NULL,
[AA_Nombre_de_Proveedor] varchar(200) NULL,
[AA_Nombre_de_Proveedor_Valid] varchar(42) NULL,
[AA_NumeroDeTelefono] varchar(100) NULL,
[AA_TFS] varchar(200) NULL,
[AA_Notas] varchar(1000) NULL,
[AA_Telefono] bigint NULL,
[LAR_Effort] int NULL,
[LAR_RRMethodTemp] int NULL,
[AA_Plantillas_incidente_Valid] varchar(42) NULL,
[AA_Plantillas_incidente] varchar(200) NULL,
[AA_Estado_CC_Valid] varchar(42) NULL,
[AA_Estado_CC] varchar(200) NULL,
[AA_Aplicaciones_Valid] varchar(42) NULL,
[AA_Aplicaciones] varchar(200) NULL,
[AA_Tipo_de_Solicitud_Valid] varchar(42) NULL,
[AA_Tipo_de_Solicitud] varchar(200) NULL,
[AA_Requiere_Aproacion_Valid] varchar(42) NULL,
[AA_Requiere_Aproacion] varchar(200) NULL,
[AA_Aprobador_Valid] varchar(42) NULL,
[AA_Aprobador] nvarchar(200) NULL,
[AA_Codigo_Empleado] varchar(200) NULL,
[AA_Departamento] varchar(200) NULL,
[AA_Asunto_Aprobacion] varchar(200) NULL,
[AA_Empleadostest] nvarchar(200) NULL,
[AA_OwnerDisplayName] nvarchar(1000) NULL,
[AA_OwnerDisplayName_Valid] varchar(42) NULL,
[AA_ModificacionResolucion] varchar(200) NULL,
[AA_ModificacionResolucionFecha] datetime NULL,
[AA_InActionIncidente_Category] varchar(100) NULL,
[AA_InActionIncidente_RecID] varchar(42) NULL,
[AA_TiempoEnEjecuccionIncident] varchar(500) NULL)
ON [PRIMARY]
TEXTIMAGE_ON [PRIMARY];
GO



----------------------4---------------------
----------------------5---------------------
----------------------6---------------------